# Generated by Django 4.2.3 on 2023-07-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_color',
            field=models.CharField(blank=True, default=True, max_length=50),
        ),
    ]
