# Generated by Django 4.2.3 on 2023-07-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_user_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='text_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
